### ISSUE TITLE
When the method of TraceEntry.php reflection does not exist? Does it need to be captured.

### ISSUE THREAD

**Issue by AuroraYolo** [chevere/trace#2]
Trace:
![image](https://user-images.githubusercontent.com/20986749/153329194-621ccb36-3650-4125-8328-9099ac5223f3.png)

Problem:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/20986749/153329286-b661792a-c627-4e1f-b48d-800ec710df8f.png">

**Comment by rodber** [comment]
Provide a sample repo where I can replicate the issue.

**Comment by rodber** [comment]
This seems to be the same as #3

**Comment by AuroraYolo** [comment]
yes, almost similar
